#76 added styling
hlxsites/24petwatch pull request #81
Opened 2024-04-23 15:23 UTC by mikeweis

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #76

Test URLs:

USA:
- Before: https://develop--24petwatch--hlxsites.hlx.page/drafts/miweis/underwriter
- After: https://76-underwriter--24petwatch--hlxsites.hlx.page/drafts/miweis/underwriter

Canada:
- Before: https://develop--24petwatch--hlxsites.hlx.page/drafts/miweis/ca/underwriter
- After: https://76-underwriter--24petwatch--hlxsites.hlx.page/drafts/miweis/ca/underwriter

2024-04-24 16:41 UTC, fe-lix- requested changes

2024-04-24 16:41 UTC, fe-lix- commented on styles/styles.css
> +main .underwriter h1 > span {
Why not just `h1 > span`? It looks more clear that Icon in title should be spaced.

2024-04-30 22:33 UTC, mikeweis commented on blocks/columns/columns.css
> +div.columns.underwriter > div > :nth-child(2) {
Updated.

2024-05-07 19:25 UTC, BaDos approved these changes

2024-05-08 13:36 UTC, merged