#82: Privacy Policy page
hlxsites/24petwatch pull request #87
Opened 2024-04-24 00:32 UTC by mikeweis

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #82

Test URLs:

USA:
- Before: https://develop--24petwatch--hlxsites.hlx.page/drafts/miweis/privacy-policy
- After: https://82-privacy-policy--24petwatch--hlxsites.hlx.page/drafts/miweis/privacy-policy

Canada:
- Before: https://develop--24petwatch--hlxsites.hlx.page/drafts/miweis/ca/privacy-policy
- After: https://82-privacy-policy--24petwatch--hlxsites.hlx.page/drafts/miweis/ca/privacy-policy

2024-04-24 15:24 UTC, fe-lix- approved these changes
LGTM

2024-04-24 16:38 UTC, fe-lix- requested changes

2024-04-24 16:38 UTC, fe-lix- commented on styles/styles.css
> +main .privacy-policy h5 {
Maybe use a `theme` or a semantic style.

2024-04-30 22:22 UTC, mikeweis commented on styles/styles.css
> +main .privacy-policy h5 {
Updated.

2024-05-07 19:11 UTC, BaDos approved these changes

2024-05-07 20:32 UTC, merged